version: '3.8'

services:
  jj-website:
    image: nginx:alpine
    container_name: jj-website-first
    ports:
      - "8082:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
    restart: unless-stopped
